### ISSUE TITLE
RN 0.80.0 support, Android build fails

### ISSUE THREAD

**Issue by isinuyk** [segmentio/analytics-react-native#1082]
- `analytics-react-native` version: 2.21.1
- Integrations versions (if used): "@segment/sovran-react-native": "^1.1.3",
- React Native version: 0.80.0 
- iOS or Android or both? Android

**Steps to reproduce**
Run android build with the latest RN version of 0.80
**Expected behavior**
Android app is built succesfully
**Actual behavior**
Class 'AnalyticsReactNativeModule' is not abstract and does not implement abstract members:
fun onActivityResult(activity: Activity, requestCode: Int, resultCode: Int, data: Intent?): Unit
fun onNewIntent(intent: Intent): Unit
AnalyticsReactNativeModule.kt:164:68 'fun String.toLowerCase(locale: Locale): String' is deprecated. Use lowercase() instead.
AnalyticsReactNativeModule.kt:242:3 'onActivityResult' overrides nothing. Potential signatures for overriding:
fun onActivityResult(activity: Activity, requestCode: Int, resultCode: Int, data: Intent?): Unit
AnalyticsReactNativeModule.kt:246:3 'onNewIntent' overrides nothing. Potential signatures for overriding:
fun onNewIntent(intent: Intent): Unit
